INSERT INTO books(id, title, author, published)
VALUES (1, 'The Hunger Games', 'Suzanne Collins', true),
       (2, 'Harry Potter and the Order of the Phoenix', 'J.K. Rowling', true),
       (3, 'Pride and Prejudice', 'Jane Austen', true),
       (4, 'To Kill a Mockingbird', 'Harper Lee', true),
       (5, 'The Book Thief', 'Markus Zusak', true),
       (6, 'Twilight', 'Stephenie Meyer', true),
       (7, 'Animal Farm', 'George Orwell', true),
       (8, 'The Chronicles of Narnia', 'C.S. Lewis', true),
       (9, 'J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings', 'J.R.R. Tolkien', true),
       (10, 'The Fault in Our Stars', 'John Green', true),
       (11, 'Gone with the Wind', 'Margaret Mitchell', true),
       (12, 'The Giving Tree', 'Shel Silverstein', true),
       (13, 'Wuthering Heights', 'Emily Brontë', true),
       (14, 'The Picture of Dorian Gray', 'Oscar Wilde', true),
       (15, 'The Da Vinci Code', 'Dan Brown', true),
       (16, 'Alice''s Adventures in Wonderland', 'Lewis Carroll', true),
       (17, 'Memoirs of a Geisha', 'Arthur Golden', true),
       (18, 'Divergent', 'Veronica Roth', true),
       (19, 'The Great Gatsby', 'F. Scott Fitzgerald', true),
       (20, 'Les Misérables', 'Victor Hugo', true);